# Generated by Django 6.0.3 on 2026-03-28 03:16

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


def generate_executive_codes(apps, schema_editor):
    Club = apps.get_model('main', 'Club')
    used = set()
    for club in Club.objects.all():
        code = secrets.token_urlsafe(15)[:20]
        while code in used:
            code = secrets.token_urlsafe(15)[:20]
        used.add(code)
        club.executive_code = code
        club.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='executive_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(generate_executive_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='club',
            name='executive_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('engineering', 'School of Engineering and Applied Science'), ('cas', 'College of Arts and Sciences'), ('commerce', 'McIntire School of Commerce'), ('architecture', 'School of Architecture'), ('education', 'School of Education and Human Development'), ('nursing', 'School of Nursing'), ('batten', 'Batten School of Leadership and Public Policy')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
