# Generated by Django 5.2.10 on 2026-03-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_club_executive_code_user_age_user_birthday_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="executive_code",
        ),
        migrations.AlterField(
            model_name="club",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
