# Generated by Django 6.0.2 on 2026-03-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True,
                choices=[
                    ("engineering", "School of Engineering and Applied Science"),
                    ("cas", "College of Arts and Sciences"),
                    ("commerce", "McIntire School of Commerce"),
                    ("architecture", "School of Architecture"),
                    ("education", "School of Education and Human Development"),
                    ("nursing", "School of Nursing"),
                    ("batten", "Batten School of Leadership and Public Policy"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1st year"),
                    ("2", "2nd year"),
                    ("3", "3rd year"),
                    ("4", "4th year"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
