# Generated by Django 6.0.2 on 2026-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_club_executive_code_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_admin',
            field=models.BooleanField(default=False),
        ),
        # executive_code was manually removed from the DB but Django state thinks it exists.
        # Update state with AlterField, but actually ADD the column in the DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='club',
                    name='executive_code',
                    field=models.CharField(blank=True, max_length=8),
                ),
            ],
            # executive_code already exists in DB from 0002 on a fresh database;
            # only update Django state, skip the ADD COLUMN.
            database_operations=[],
        ),
    ]
