# Generated by Django 5.2.10 on 2026-04-14 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_forum_forumthread_forumreply"),
        ("main", "0010_alter_user_age_alter_user_profile_picture"),
    ]

    operations = []
