# Generated by Django 5.2.10 on 2026-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_merge_20260414_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="executive_code",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("social", "Social"),
                    ("academic", "Academic"),
                    ("entertainment", "Entertainment"),
                    ("professional", "Professional"),
                    ("cultural", "Cultural"),
                    ("sports", "Sports"),
                    ("arts", "Arts"),
                    ("technology", "Technology"),
                    ("services", "Services"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
