# Generated by Django 5.2.10 on 2026-04-14 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_club_executive_code_event_category_event_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
    ]
