# Generated by Django 5.2.10 on 2026-04-24 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
    ]
