# Generated by Django 6.0.2 on 2026-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_clubsettings_joinrequest_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_clubs',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='main.club'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1, null=True),
        ),
    ]
