# Generated by Django 5.2.10 on 2026-04-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_user_saved_clubs_alter_user_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumreply",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="forumreply",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
