# Generated by Django 5.2.10 on 2026-04-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_forumreply_is_deleted_forumreply_is_pinned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumreply",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="forumreply",
            name="is_pinned",
        ),
        migrations.AddField(
            model_name="forumthread",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
