# Generated by Django 5.2.10 on 2026-04-27 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_announcement_type_polloption_pollvote"),
        ("main", "0018_remove_forumreply_is_deleted_and_more"),
    ]

    operations = []
