# Generated by Django 6.0.2 on 2026-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_highlight_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
