# Generated by Django 5.2.10 on 2026-04-27 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_merge_20260427_0955"),
        ("main", "0021_highlight_model"),
    ]

    operations = []
