# Generated by Django 5.2.10 on 2026-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_merge_0019_merge_20260427_0955_0021_highlight_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
