# Generated by Django 6.0.2 on 2026-04-28 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_eventnotificationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(upload_to='club_ads/')),
                ('week_start', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='main.club')),
            ],
            options={
                'unique_together': {('club', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='AdBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_of_week', models.PositiveSmallIntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.clubad')),
            ],
            options={
                'unique_together': {('ad', 'hour_of_week')},
            },
        ),
    ]
