# Generated by Django 6.0.2 on 2026-04-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_facebook_url_event_instagram_url_event_tags_and_more'),
        ('main', '0025_clubad_adbooking'),
    ]

    operations = [
    ]
