from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
import secrets
import os
from uuid import uuid4
from datetime import date

def rename_image(instance, filename): # rename function generated by google search AI with prompt "django image field renaming"
    upload_to = 'profile_pics/'
    ext = filename.split('.')[-1]
    # Use UUID to ensure unique names and prevent overwriting
    filename = f'{uuid4().hex}.{ext}'
    return os.path.join(upload_to, filename)

def validate_birthday(value):
    today = date.today()
    age = today.year - value.year - ((today.month, today.day) < (value.month, value.day))
    if age > 118:
        raise ValidationError('Age cannot exceed 120 years old.')
    if value > today:
        raise ValidationError('Birthday cannot be in the future.')

class User(AbstractUser):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    profile_slug = models.SlugField(unique=True, blank=True)

    YEAR_CHOICES = [
        ('1', '1st Year'),
        ('2', '2nd Year'),
        ('3', '3rd Year'),
        ('4', '4th Year'),]

    SCHOOL_CHOICES = [
        ('engineering', 'School of Engineering and Applied Science'),
        ('cas', 'College of Arts and Sciences'),
        ('commerce', 'McIntire School of Commerce'),
        ('architecture', 'School of Architecture'),
        ('education', 'School of Education and Human Development'),
        ('nursing', 'School of Nursing'),
        ('batten', 'Batten School of Leadership and Public Policy'),
    ]

    is_user_admin = models.BooleanField(default=False)
    profile_picture = models.ImageField(upload_to=rename_image, blank=True, null=True)

    birthday = models.DateField(null=True, blank=True)
    year = models.CharField(max_length = 1, choices = YEAR_CHOICES, blank=True, null=True)
    school = models.CharField(max_length = 50, choices = SCHOOL_CHOICES, blank=True, null=True)
    saved_clubs = models.ManyToManyField('Club', blank=True, related_name='saved_by')

    @property
    def age(self):
        if self.birthday:
            today = date.today()
            return today.year - self.birthday.year - ( #calculate age through the birthday
                (today.month, today.day) < (self.birthday.month, self.birthday.day)
            )
        return None

    def save(self, *args, **kwargs):
        if not self.profile_slug:
            self.profile_slug = slugify(self.username)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username


class Club(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True, blank=True)
    executive_code = models.CharField(max_length=8, blank=True)
    image = models.ImageField(upload_to='club_images/', blank=True, null=True)
    profile_picture = models.ImageField(upload_to='club_profile_pics/', blank=True, null=True)
    tags = models.CharField(max_length=500, blank=True)
    socials = models.JSONField(default=list, blank=True)

    @property
    def tags_list(self):
        return [t.strip() for t in self.tags.split(',') if t.strip()]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        if not self.executive_code:
            self.executive_code = secrets.token_hex(4)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Membership(models.Model):
    EXECUTIVE = 'executive'
    MEMBER = 'member'
    ROLE_CHOICES = [
        (EXECUTIVE, 'Executive'),
        (MEMBER, 'General Member'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='memberships')
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='memberships')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=MEMBER)

    class Meta:
        unique_together = ('user', 'club')

    def __str__(self):
        return f"{self.user} - {self.club} ({self.role})"

#basic event setup - to be edited
class Event(models.Model):
    CATEGORY_CHOICES = [
        ('social', 'Social'),
        ('academic', 'Academic'),
        ('entertainment', 'Entertainment'),
        ('professional', 'Professional'),
        ('cultural', 'Cultural'),
        ('sports', 'Sports'),
        ('arts', 'Arts'),
        ('technology', 'Technology'),
        ('services', 'Services'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    time = models.TimeField()
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)

    location = models.CharField(max_length=200)

    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='events')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    rsvps = models.ManyToManyField(User, related_name='rsvped_events', blank=True)
    image = models.ImageField(upload_to='event_images/', blank=True, null=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, blank=True)

    def __str__(self):
        return self.title

class Forum(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='forums')

    def __str__(self):
        return f"Forum for {self.club.name}"

class ForumThread(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE, related_name='threads')
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_threads', blank=True)

    def __str__(self):
        return self.title

class ForumReply(models.Model):
    thread = models.ForeignKey(ForumThread, on_delete=models.CASCADE, related_name='replies')
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_replies', blank=True)

    def __str__(self):
        return f"Reply by {self.author} on {self.thread}"

# ──────────────────────────────────────────────
# ANNOUNCEMENTS
# ──────────────────────────────────────────────

class Announcement(models.Model):
    MEMBERS = 'members'
    EVERYONE = 'everyone'
    VISIBILITY_CHOICES = [
        (MEMBERS, 'Club Members Only'),
        (EVERYONE, 'Everyone'),
    ]
    MESSAGE = 'message'
    POLL = 'poll'
    TYPE_CHOICES = [(MESSAGE, 'Message'), (POLL, 'Poll')]

    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='announcements')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)
    content = models.TextField()
    visibility = models.CharField(max_length=10, choices=VISIBILITY_CHOICES, default=EVERYONE)
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default=MESSAGE)
    allow_other = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.club.name}: {self.title}"


class PollOption(models.Model):
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE, related_name='poll_options')
    text = models.CharField(max_length=300)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.text


class PollVote(models.Model):
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE, related_name='poll_votes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    option = models.ForeignKey(PollOption, on_delete=models.SET_NULL, null=True, blank=True)
    other_text = models.CharField(max_length=500, blank=True)

    class Meta:
        unique_together = ('announcement', 'user')

# ──────────────────────────────────────────────
# MESSAGING MODELS
# ──────────────────────────────────────────────

class DirectMessage(models.Model):
    """A private message between two users."""
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_dms')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_dms')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"DM from {self.sender} to {self.recipient}"
    
    
# ──────────────────────────────────────────────
# Club Management Models
# ──────────────────────────────────────────────

class ClubSettings(models.Model):
    club = models.OneToOneField(Club, on_delete=models.CASCADE, related_name = 'settings')
    require_approval = models.BooleanField(default=False) #toggle button basically

class JoinRequest(models.Model):
    #This tracks the pending/approved/rejected requested when approval is required
    PENDING = 'pending'
    APPROVED = 'approved'
    REJECTED = 'rejected'
    STATUS_CHOICES = [(PENDING, 'Pending'), (APPROVED, 'Approved'), (REJECTED, 'Rejected')]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='join_requests')
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='join_requests')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PENDING)
    created_at = models.DateTimeField(auto_now_add=True)

class Ban(models.Model):
    # Records who banned whom and when
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bans')
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='bans')
    banned_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bans_issued')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'club'),)


class Highlight(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='highlights')
    image = models.ImageField(upload_to='club_highlights/')
    caption = models.CharField(max_length=300, blank=True)
    order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order', 'created_at']

    def __str__(self):
        return f"Highlight for {self.club.name} #{self.order}"

